export const divisions = [
	{
		logo: '/logo/goin/department/kerox.webp',
		title: 'KEROX',
		description: 'Kerox adalah singkatan dari Keringat Orthodox. Unit olahraga bersama lintas paroki dan komox dalam GOIN.',
		link: 'https://chat.whatsapp.com/DbNx543QWHuCJlcsttuQFQ',
		href: '',
		label: '',
		ambient: '#AC9CC7',
	},
	{
		logo: '/logo/goin/department/ortholadies.png',
		title: 'Ortholadies',
		description: 'Ortholadies (<i>Daughters of the Vine</i>) adalah divisi khusus untuk para wanita orthodox di GOI.',
		link: 'https://chat.whatsapp.com/H77ktrQ9R0r279ozhTx6QA',
		href: '',
		label: '',
		ambient: '#E8999F',
	},
	{
		logo: '/logo/goin/department/g3.png',
		title: 'GGG',
		description: 'GGG (<i>GOIN Gamers Guild</i>) adalah unit gaming bersama lintas paroki dan komox dalam GOIN.',
		link: 'https://chat.whatsapp.com/GWLcWOpwikU0sjuuaQfOEs',
		href: '',
		label: '',
		ambient: '#C57F75',
	},
	{
		logo: '/logo/goin/department/business.svg',
		title: 'ABS',
		description: 'Aliansi Bisnis dan Service adalah divisi para penyedia jasa, produk, pebisnis maupun professional dalam GOIN.',
		link: 'https://chat.whatsapp.com/L9mC4vVCDqP43aPQ3lfxg2',
		href: '/abs',
		label: '',
		ambient: '#AC9CC7',
	},
	{
		logo: '/logo/goin/solid/goin-beige-red.svg',
		title: 'Kidung',
		description: 'Unit penyebaran info dan belajar untuk para anagnostis dan juga umat yang tertarik dengan perkidungan orthodox.',
		link: 'https://chat.whatsapp.com/EujitYm7DXCKXkqTNgF2dM',
		href: '/kidung',
		label: '',
		ambient: '#D7A593',
	},
	{
		logo: '/logo/goin/solid/goin-beige-red.svg',
		title: 'Dokumen',
		description: 'Unit sharing file, baik PDF buku, PDF liturgi, maupun tulisan-tulisan yang berhubungan dengan orthodoxy.',
		link: 'https://chat.whatsapp.com/CQQ5wzzMSJl5ZEW7NfyavA',
		href: '',
		label: '',
		ambient: '#D7A593',
	},
	{
		logo: '/logo/goin/department/orthofood.png',
		title: 'Orthofood',
		description: 'Divisi sharing resep makanan-makanan yang ramah dengan puasa orthodox, maupun makanan biasa lainnya.',
		link: 'https://chat.whatsapp.com/IepH9wcoehdCWKUeTPzQzg',
		href: '#',
		label: '',
		ambient: '#C09F7C',
	},
	{
		logo: '/logo/goin/solid/goin-black-red.svg',
		title: 'Belajar Bersama',
		description: 'Unit sharing dan belajar, juga menjadi tempat bertanya kepada pada Klerus yang bergabung juga dalam grup.',
		link: 'https://chat.whatsapp.com/KQQ0GHGban53XNhACDBNQ1',
		href: '',
		label: '',
		ambient: '#D7A593',
	},
]

export const projects = [
	{
		logo: '/logo/goi.png',
		title: 'Standarisasi Kidungan',
		description: 'Web untuk membantu penyebaran standarisasi nada yang dikepalai Romo Martinos.',
		link: '',
		href: '/kidung',
		label: '',
		ambient: '#E4CB91',
	},
	{
		logo: '/logo/goi.png',
		title: 'Web Paroki & Komox',
		description: 'Pembuatan website untuk Paroki dan Komox GOI yang membutuhkan, tidak dipungut biaya.',
		link: '',
		href: '#',
		label: 'Kontak',
		ambient: '#E4CB91',
	},
	{
		logo: '/logo/goin/department/slb.svg',
		title: 'Singsing Lengan Baju',
		description: 'Divisi khusus untuk berkerja, berkarya secara gerilya dalam GOI. Group berfokus pada kontribusi kerja dan support dari GOIN pada GOI.',
		link: '',
		href: '',
		label: '',
		ambient: '#666',
	},
	{
		logo: '/logo/goin/solid/goin-beige-red.svg',
		title: 'Public Chat',
		description: 'Ruang chatting publik tempat bercanda dan sharing harian para umat lintas GOI.',
		link: 'https://chat.whatsapp.com/IBiV370GYkAGEZqXjQHo8c',
		href: '',
		label: '',
		ambient: '#D7A593',
	},
]